"""empty message

Revision ID: 7207a2cdc367
Revises: a33b0edd4279
Create Date: 2023-02-16 09:54:39.761391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7207a2cdc367'
down_revision = 'a33b0edd4279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toatal_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('toatal_price')

    # ### end Alembic commands ###
