"""empty message

Revision ID: 858d1154a59f
Revises: 5cb06b737a7d
Create Date: 2023-02-15 15:26:44.106675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858d1154a59f'
down_revision = '5cb06b737a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.String(length=25), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
