"""empty message

Revision ID: b19ae065daf6
Revises: 7207a2cdc367
Create Date: 2023-02-16 09:56:59.888003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19ae065daf6'
down_revision = '7207a2cdc367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('toatal_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toatal_price', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
